[project]
name = "paper-transito"
version = "0.1.0"
description = ""
authors = [
    {name = "Ana Jaramillo",email = "anmjaramillo@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "openpyxl",
    "missingno",
    "setuptools",
    "ipykernel",
    "sweetviz",
    "scikit-learn",
    "pycaret",
    "kaleido (==0.2.1)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
