[project]
name = "paper-transito"
version = "0.1.0"
description = ""
authors = [
    {name = "Ana Jaramillo",email = "anmjaramillo@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy (==1.23.5)",
    "pandas (==1.4.3)",
    "openpyxl (==3.0.10)",
    "missingno (==0.5.0)",
    "setuptools (==78.0.1)",
    "ipykernel (==6.9.1)",
    "sweetviz (==2.1.3)",
    "scikit-learn (==1.1.3)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
